# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#General
title: Portfolio Lucas M Carvalhaes
inner_title: Portfolio

#SEO
description: Developer portfolio for the game developer, Unity 3D developer, Virtual Reality developer, augmented reality developer, systems architect Lucas Montenegro Carvalhaes.

author:
  twitter: zombiemontec
  gitlab: lucasmontec
  github: lucasmontec
  
social:
  name: Lucas Montenegro Carvalhaes
  links:
    - https://twitter.com/zombiemontec
    - https://www.linkedin.com/in/javaman
    - https://github.com/lucasmontec
    - https://gitlab.com/lucasmontec
    
lang: en_US

#Banner
banner_video: https://www.youtube.com/embed/jP7aozy4TJg?controls=0&showinfo=0&rel=0&playlist=jP7aozy4TJg&autoplay=1&loop=1&mute=1
banner_header: Lucas Montenegro Carvalhaes
banner_description: Game development aficionado. C# enthusiast.<br/>Scroll down to checkout my work. Have fun!

#Content

#Direct link
direct_link_header: Go check it out
direct_link_button: Go There

#All projects button
all_projects_section_header: More
all_projects_section_subtitle: Other interesting stuff I've done...

#Contact me
contact_header: Contact me
#Optional contact phrase
contact_phrase: >- # Multiline
    Do you want to work with me, want to use my code somewhere? Have questions about networking or game development?
email_button: Feel free to drop me an email!

#Footer
twitter_user: zombiemontec
linkedin_tag: javaman
gitlab_user: lucasmontec
github_user: lucasmontec
bitbucket_user: lucasmontec

email: lucas.mcarvalhaes@gmail.com
email_subject: Contact
description: >- # this means to ignore newlines until "baseurl:"
  Game development aficionado. C# enthusiast.
  Scroll down to checkout my work. Have fun!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lucasmontec.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

copyright_notice: "&copy; Lucas M Carvalhaes. All rights reserved."

# Build settings
markdown: kramdown
# theme: minima
mermaid: true

google_analytics: UA-142152268-1

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mermaid

collections:
    projects:
        output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      project: true
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      post: true
      layout: "post"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
